import * as XLSX from 'xlsx';import type { TmMaster,SeverityMaster } from '../types/tm';import type { ReplacementHistory } from '../types/replacement';import type { RiskScore,ValidationIssue } from '../types/risk';import { keepLatestTmByCurrentLocation } from './tmState';
export interface ParsedWorkbook{fileName:string;sheetNames:string[];selectedSheet:string;headers:string[];rows:Record<string,unknown>[];headerRow:number;raw:Array<Array<unknown>>;}
export type SeverityMap=Map<string,SeverityMaster>;
export const UNKNOWN_VALUE='모름';
const nowIso=()=>new Date().toISOString();
const text=(v:unknown)=>v==null?'':String(v).trim();
const knownText=(v:unknown)=>text(v)||UNKNOWN_VALUE;
const isUnknown=(v:unknown)=>!text(v)||text(v)===UNKNOWN_VALUE;
const isExcelError=(v:unknown)=>/^#(NAME|VALUE|REF|DIV\/0|N\/A|NULL|NUM)\!?$/i.test(text(v));
const num=(v:unknown)=>{if(isExcelError(v))return null;const s=text(v).replace(/,/g,'');const n=Number(s);return Number.isFinite(n)?n:null;};
const date=(v:unknown)=>{if(!v||isExcelError(v))return'';if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?d.y+'-'+String(d.m).padStart(2,'0')+'-'+String(d.d).padStart(2,'0'):'';}const s=text(v).replace(/[./]/g,'-');const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toISOString().slice(0,10);};
export const normalizeSerial=(value:unknown)=>text(value).replace(/\s+/g,' ');
export const normalizeHeader=(header:unknown)=>text(header).toLowerCase().replace(/[\s._\-()[\]/\\:·,]+/g,'').replace(/[（）]/g,'');
const normalizeKey=(value:unknown)=>text(value).toLowerCase().replace(/\s+/g,'');
const uniqueHeaders=(row:Array<unknown>)=>{const seen=new Map<string,number>();return row.map((v,i)=>{const base=text(v)||'빈컬럼'+(i+1);const count=seen.get(base)??0;seen.set(base,count+1);return count?base+'_'+(count+1):base;});};
const rawSheet=(sheet:XLSX.WorkSheet)=>XLSX.utils.sheet_to_json<Array<unknown>>(sheet,{header:1,defval:'',raw:false});
const bestHeaderRow=(raw:Array<Array<unknown>>)=>{let headerRow=0,best=-1;raw.slice(0,25).forEach((r,i)=>{const filled=r.filter(v=>text(v)).length;const labelScore=r.filter(v=>/[가-힣A-Za-z]/.test(text(v))).length;const score=filled+labelScore;if(score>best){best=score;headerRow=i;}});return headerRow;};
const rowsFromRaw=(raw:Array<Array<unknown>>)=>{const headerRow=bestHeaderRow(raw);const headers=uniqueHeaders(raw[headerRow]??[]);const rows=raw.slice(headerRow+1).filter(r=>r.some(v=>text(v))).map((r,i)=>({...Object.fromEntries(headers.map((h,j)=>[h,r[j]??''])),__rowNumber:headerRow+i+2}));return{headers,rows,headerRow:headerRow+1};};
export function mapHeaders(row:Array<unknown>){return new Map(row.map((h,i)=>[normalizeHeader(h),i]));}
export function findSheetByName(workbook:XLSX.WorkBook,possibleNames:string[]){const names=possibleNames.map(normalizeHeader);const exact=workbook.SheetNames.find(name=>names.includes(normalizeHeader(name)));if(exact)return exact;return workbook.SheetNames.find(name=>names.some(n=>normalizeHeader(name).includes(n)||n.includes(normalizeHeader(name))));}
export async function readWorkbookFromFile(file:File){return XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});}
export async function parseWorkbook(file:File,sheetName?:string):Promise<ParsedWorkbook>{const wb=await readWorkbookFromFile(file);const selectedSheet=sheetName&&wb.Sheets[sheetName]?sheetName:wb.SheetNames[0];const raw=rawSheet(wb.Sheets[selectedSheet]);const parsed=rowsFromRaw(raw);return{fileName:file.name,sheetNames:wb.SheetNames,selectedSheet,headers:parsed.headers,rows:parsed.rows,headerRow:parsed.headerRow,raw};}
const has=(row:Record<string,unknown>,key:string)=>Object.prototype.hasOwnProperty.call(row,key);
const pick=(row:Record<string,unknown>,...aliases:string[])=>{for(const alias of aliases){const found=Object.keys(row).find(k=>normalizeHeader(k)===normalizeHeader(alias));if(found&&has(row,found))return row[found];}return'';};
const severityKey=(failureType:string)=>normalizeKey(failureType);
export function parseSeverityClassificationSheet(workbook:XLSX.WorkBook):SeverityMaster[]{const name=findSheetByName(workbook,['고장심각도분류','severity']);if(!name)throw new Error('필수 시트가 없습니다: 고장심각도분류');const {rows}=rowsFromRaw(rawSheet(workbook.Sheets[name]));return rows.map(row=>({failureCode:text(pick(row,'고장코드')),failureType:text(pick(row,'표준고장유형')),severityClass:text(pick(row,'심각도')),severityScore:num(pick(row,'위험점수'))??0,description:text(pick(row,'비고','설명')),isActive:true})).filter(v=>v.failureType&&v.failureCode);}
export function toSeverityMap(severities:SeverityMaster[]):SeverityMap{return new Map(severities.map(s=>[severityKey(s.failureType),s]));}
export function calculateFailureSeverity<T extends Partial<ReplacementHistory>>(replacementRow:T,severityMap:SeverityMap):T{const sev=severityMap.get(severityKey(replacementRow.failureType||''));return{...replacementRow,failureCode:sev?.failureCode||'',severityClass:sev?.severityClass||'',severityScore:sev?sev.severityScore:null};}
export function mapTmRows(rows:Record<string,unknown>[],m:Record<string,string>,referenceYear:number):TmMaster[]{const now=nowIso();return rows.map<TmMaster>(r=>{const year=num(r[m.manufactureYear]);const status=knownText(r[m.currentStatus]);const spare=['예','y','true','1','예비품'].includes(text(r[m.isSpare]).toLowerCase())||status.includes('예비');const car=text(r[m.currentCar])||text(r[m.currentUnit]);return{tmId:text(r[m.tmId]),serialNo:normalizeSerial(r[m.serialNo]),manufacturer:knownText(r[m.manufacturer]),manufactureYear:year,ageYear:year?Math.max(0,referenceYear-year):0,currentStatus:status,currentTrain:text(r[m.currentTrain]),currentCar:car,currentUnit:text(r[m.currentUnit])||car,currentPosition:text(r[m.currentPosition]),installDate:date(r[m.installDate]),isSpare:spare,sourceType:'current_excel',locationSource:'현황파일',inferredFromReplacement:false,inferredReplacementDate:'',note:text(r[m.note]),createdAt:now,updatedAt:now};}).filter(v=>v.serialNo&&v.serialNo!=='-');}
export function parseTMInstallationSheet(workbook:XLSX.WorkBook,referenceYear=2026):TmMaster[]{const name=findSheetByName(workbook,['01_TM_취부현황','TM 취부 현황','취부현황']);if(!name)throw new Error('필수 시트가 없습니다: 01_TM_취부현황');const {rows}=rowsFromRaw(rawSheet(workbook.Sheets[name]));return keepLatestTmByCurrentLocation(mapTmRows(rows,{tmId:'TM_ID',serialNo:'시리얼번호',manufacturer:'제조사',manufactureYear:'제작년도',currentStatus:'현재상태',isSpare:'현재상태',currentTrain:'편성',currentCar:'차호',currentUnit:'위수',currentPosition:'위치',installDate:'교환일자',note:'현황비고'},referenceYear));}
export function mapReplacementRows(rows:Record<string,unknown>[],m:Record<string,string>,severityMap?:SeverityMap):ReplacementHistory[]{const now=nowIso();return rows.map<ReplacementHistory>(r=>{const base:ReplacementHistory={replacementId:text(r[m.replacementId])||crypto.randomUUID(),replacementDate:date(r[m.replacementDate]),trainNo:knownText(r[m.trainNo]),carNo:text(r[m.carNo]),position:knownText(r[m.position]),removedSerialNo:normalizeSerial(r[m.removedSerialNo]),removedManufactureYear:num(r[m.removedManufactureYear]),removedManufacturer:knownText(r[m.removedManufacturer]),removedStatus:knownText(r[m.removedStatus]),installedSerialNo:normalizeSerial(r[m.installedSerialNo]),installedManufactureYear:num(r[m.installedManufactureYear]),installedManufacturer:knownText(r[m.installedManufacturer]),installedStatus:knownText(r[m.installedStatus]),replacementReason:text(r[m.replacementReason]),failureType:knownText(r[m.failureType]),failureCode:'',severityClass:text(r[m.severityClass]),severityScore:num(r[m.severityScore]),failureReplacement:text(r[m.failureReplacement]),detail:knownText(r[m.detail]),actionTaken:text(r[m.actionTaken]),note:text(r[m.note]),inputSource:'history_excel',createdAt:now,updatedAt:now};return severityMap?calculateFailureSeverity(base,severityMap):base;}).filter(v=>(v.replacementDate||v.removedSerialNo||v.installedSerialNo)&&(v.removedSerialNo!=='-'||v.installedSerialNo!=='-'));}
export function parseReplacementHistorySheet(workbook:XLSX.WorkBook,severityMap=toSeverityMap(parseSeverityClassificationSheet(workbook))):ReplacementHistory[]{const name=findSheetByName(workbook,['교체현황_DB','교체현황']);if(!name)throw new Error('필수 시트가 없습니다: 교체현황_DB');const {rows}=rowsFromRaw(rawSheet(workbook.Sheets[name]));return mapReplacementRows(rows,{replacementId:'교체ID',replacementDate:'교체일자',trainNo:'편성',carNo:'차호',position:'위치',removedSerialNo:'취거TM_시리얼',removedManufactureYear:'취거TM_제작년도',removedManufacturer:'취거TM_제조사',removedStatus:'취거품 상태(선택)',installedSerialNo:'부착TM_시리얼',installedManufactureYear:'부착TM_제작년도',installedManufacturer:'부착TM_제조사',installedStatus:'',replacementReason:'',failureType:'고장유형(선택)',severityClass:'',severityScore:'위험점수(자동)',failureReplacement:'고장성교체여부(자동)',detail:'세부 고장내용',actionTaken:'',note:'취거품 상태/조치비고'},severityMap);}
const issue=(level:ValidationIssue['level'],category:string,message:string,recommendation:string,sheetName?:string,row?:number,serialNo?:string):ValidationIssue=>({id:crypto.randomUUID(),level,category,sheetName,row,serialNo,message,recommendation});
export function validateMasterRows(masterRows:TmMaster[]):ValidationIssue[]{const out:ValidationIssue[]=[];const seen=new Set<string>();const positions=new Map<string,string>();masterRows.forEach((tm,i)=>{const row=i+2,isSpare=tm.currentStatus==='예비품'||tm.isSpare;if(!tm.serialNo)out.push(issue('오류','시리얼번호 누락','취부현황에서 시리얼번호가 없습니다.','시리얼번호는 TM 식별키라 입력이 필요합니다.','01_TM_취부현황',row));else if(seen.has(tm.serialNo))out.push(issue('오류','중복 Serial No.',tm.serialNo+'가 중복되었습니다.','중복 시리얼번호를 확인하세요.','01_TM_취부현황',row,tm.serialNo));else seen.add(tm.serialNo);if(tm.inferredFromReplacement)out.push(issue('안내','위치정보 보완','현황파일에 위치 정보가 부족하여 교체현황의 최신 부착이력 기준으로 차호/위치를 보완했습니다.','현황파일의 차호/위치 정보 보완을 권장합니다.','01_TM_취부현황',row,tm.serialNo));if(tm.currentPosition==='위치확인필요')out.push(issue('경고','위치확인필요','현황파일과 교체현황 모두에서 현재 위치를 확정할 수 없어 위치확인필요로 표시했습니다.','현황파일에 차호/위치 정보를 보완하거나, 교체현황의 부착TM 이력을 확인하세요.','01_TM_취부현황',row,tm.serialNo));if(tm.locationDateMismatch)out.push(issue('경고','날짜 불일치','현황파일 교환일자와 교체현황 최신 부착일자가 일치하지 않습니다. 현재상태 기준은 현황파일로 유지하고, 위치 정보만 교체이력을 참고했습니다.','현황파일 교환일자와 교체현황 교체일자를 확인하세요.','01_TM_취부현황',row,tm.serialNo));if(isUnknown(tm.currentStatus)||tm.currentStatus==='상태확인필요')out.push(issue('안내','현재상태 불분명','취부현황 현재상태가 불분명하여 상태확인필요로 반영되었습니다.','리스크 산출 시 불분명 항목으로 표시됩니다.','01_TM_취부현황',row,tm.serialNo));if(!tm.manufactureYear)out.push(issue('안내','제작년도 불분명','제작년도가 없어 모름으로 취급됩니다.','노후도 점수 산출이 불분명할 수 있습니다.','01_TM_취부현황',row,tm.serialNo));if(isUnknown(tm.manufacturer))out.push(issue('안내','제조사 불분명','제조사가 모름으로 반영되었습니다.','고장빈도 그룹 산출이 불분명할 수 있습니다.','01_TM_취부현황',row,tm.serialNo));if(isSpare){if(tm.currentTrain&&tm.currentTrain!=='예비품'&&!isUnknown(tm.currentTrain))out.push(issue('경고','예비품 편성 확인','예비품의 편성 값이 예비품이 아닙니다.','예비품이면 편성을 예비품으로 입력하세요.','01_TM_취부현황',row,tm.serialNo));return;}if(tm.currentStatus.includes('운영')||tm.currentStatus.includes('운행')){if(isUnknown(tm.currentTrain))out.push(issue('안내','운영중 편성 불분명','운영중 TM의 편성이 모름으로 반영되었습니다.','리스크 산출 시 불분명 항목으로 표시됩니다.','01_TM_취부현황',row,tm.serialNo));else if(!/^\d+$/.test(tm.currentTrain))out.push(issue('경고','운영중 편성 확인','운영중 TM의 편성이 실제 편성번호가 아닙니다.','편성번호를 숫자로 입력하세요.','01_TM_취부현황',row,tm.serialNo));if(isUnknown(tm.currentPosition))out.push(issue('안내','운영중 위치 불분명','운영중 TM의 위치가 모름으로 반영되었습니다.','리스크 산출 시 불분명 항목으로 표시됩니다.','01_TM_취부현황',row,tm.serialNo));else if(!/^M\d{2}$/i.test(tm.currentPosition))out.push(issue('경고','운영중 위치 확인','운영중 TM의 위치가 실제 TM 위치 형식이 아닙니다.','M01~M24 형식으로 입력하세요.','01_TM_취부현황',row,tm.serialNo));}const p=tm.currentTrain+'|'+tm.currentPosition;if(tm.currentPosition&&!isUnknown(tm.currentTrain)&&!isUnknown(tm.currentPosition)){if(positions.has(p))out.push(issue('오류','중복 취부 위치',p+' 위치에 '+positions.get(p)+'와 함께 취부되어 있습니다.','중복 위치를 수정하세요.','01_TM_취부현황',row,tm.serialNo));positions.set(p,tm.serialNo);}});return out;}
export function validateReplacementRows(replacementRows:ReplacementHistory[],masterRows:TmMaster[],severityMap:SeverityMap):ValidationIssue[]{const out:ValidationIssue[]=[];const master=new Set(masterRows.map(tm=>tm.serialNo));replacementRows.forEach((r,i)=>{const row=i+2,sn=r.removedSerialNo||r.installedSerialNo;if(!r.replacementDate)out.push(issue('안내','교체일자 불분명','교체일자가 없어 리스크 산출 이력의 시점이 불분명합니다.','확인 가능하면 교체일자를 입력하세요.','교체현황_DB',row,sn));if(isUnknown(r.trainNo))out.push(issue('안내','편성 불분명','편성이 모름으로 반영되었습니다.','리스크 산출 시 불분명 항목으로 표시됩니다.','교체현황_DB',row,sn));if(isUnknown(r.position))out.push(issue('안내','위치 불분명','위치가 모름으로 반영되었습니다.','리스크 산출 시 불분명 항목으로 표시됩니다.','교체현황_DB',row,sn));if(!r.removedSerialNo)out.push(issue('안내','취거TM 시리얼 불분명','취거TM_시리얼이 없어 취거 TM 연결이 불분명합니다.','확인 가능하면 취거 TM 시리얼번호를 입력하세요.','교체현황_DB',row,r.installedSerialNo));if(!r.installedSerialNo)out.push(issue('안내','부착TM 시리얼 불분명','부착TM_시리얼이 없어 부착 TM 연결이 불분명합니다.','확인 가능하면 부착 TM 시리얼번호를 입력하세요.','교체현황_DB',row,r.removedSerialNo));if(isUnknown(r.failureType))out.push(issue('안내','고장유형 불분명','고장유형이 모름으로 반영되었습니다.','고장 심각도 점수는 불분명 항목으로 표시됩니다.','교체현황_DB',row,sn));else if(!severityMap.has(severityKey(r.failureType)))out.push(issue('경고','고장유형 매칭 확인',r.failureType+'이 고장심각도분류 표준고장유형과 매칭되지 않습니다.','고장심각도분류의 표준고장유형과 동일하게 입력하세요.','교체현황_DB',row,sn));if(!r.removedManufactureYear)out.push(issue('안내','취거 TM 제작년도 불분명','취거 TM 제작년도가 없어 모름으로 취급됩니다.','확인 가능하면 제작년도를 입력하세요.','교체현황_DB',row,r.removedSerialNo));if(isUnknown(r.removedManufacturer))out.push(issue('안내','취거 TM 제조사 불분명','취거 TM 제조사가 모름으로 반영되었습니다.','확인 가능하면 제조사를 입력하세요.','교체현황_DB',row,r.removedSerialNo));if(!r.installedManufactureYear)out.push(issue('안내','부착 TM 제작년도 불분명','부착 TM 제작년도가 없어 모름으로 취급됩니다.','확인 가능하면 제작년도를 입력하세요.','교체현황_DB',row,r.installedSerialNo));if(isUnknown(r.installedManufacturer))out.push(issue('안내','부착 TM 제조사 불분명','부착 TM 제조사가 모름으로 반영되었습니다.','확인 가능하면 제조사를 입력하세요.','교체현황_DB',row,r.installedSerialNo));if(isUnknown(r.detail))out.push(issue('안내','세부 고장내용 불분명','세부 고장내용이 모름으로 반영되었습니다.','확인 가능하면 세부 고장내용을 입력하세요.','교체현황_DB',row,sn));if(isUnknown(r.removedStatus))out.push(issue('안내','취거품 상태 불분명','취거품 상태가 모름으로 반영되었습니다.','확인 가능하면 취거품 상태를 입력하세요.','교체현황_DB',row,r.removedSerialNo));if(!r.note)out.push(issue('안내','취거품 상태/조치비고 없음','취거품 상태/조치비고가 없습니다.','필요 시 조치비고를 입력하세요.','교체현황_DB',row,sn));[r.removedSerialNo,r.installedSerialNo].filter(Boolean).forEach(serial=>{if(!master.has(serial))out.push(issue('경고','이력만 존재 TM',serial+'는 취부현황 마스터에 없습니다.','과거 교체이력만 존재할 수 있으면 그대로 반영 가능합니다.','교체현황_DB',row,serial));});});return out;}
export function buildCleanDatabase(masterRows:TmMaster[],replacementRows:ReplacementHistory[],severityMap:SeverityMap){return{masterRows:masterRows.map(tm=>({...tm,serialNo:normalizeSerial(tm.serialNo)})),replacementRows:replacementRows.map(row=>calculateFailureSeverity({...row,removedSerialNo:normalizeSerial(row.removedSerialNo),installedSerialNo:normalizeSerial(row.installedSerialNo)},severityMap))};}
const tmHeaders:Record<keyof TmMaster,string>={tmId:'TM_ID',currentTrain:'편성',currentCar:'차호',currentPosition:'위치',installDate:'교환일자',serialNo:'시리얼번호',manufacturer:'제조사',manufactureYear:'제작년도',ageYear:'사용연수',currentStatus:'현재상태',locationSource:'위치정보 출처',inferredFromReplacement:'위치보완 여부',inferredReplacementDate:'보완 기준 교체일자',note:'현황비고',isSpare:'예비품 여부',currentUnit:'위수',sourceType:'데이터 출처',locationDateMismatch:'날짜 불일치 여부',locationDateWarning:'날짜 불일치 내용',createdAt:'생성일시',updatedAt:'수정일시'};
const replacementHeaders:Record<keyof ReplacementHistory,string>={replacementId:'교체 ID',replacementDate:'교체일자',trainNo:'편성',carNo:'호차',position:'위치',removedSerialNo:'취거 TM',removedManufactureYear:'취거 TM 제작년도',removedManufacturer:'취거 TM 제조사',removedStatus:'취거품 상태',installedSerialNo:'취부 TM',installedManufactureYear:'취부 TM 제작년도',installedManufacturer:'취부 TM 제조사',installedStatus:'취부품 상태',replacementReason:'교체사유',failureType:'고장유형',failureCode:'고장코드',severityClass:'고장심각도',severityScore:'위험점수',failureReplacement:'고장성교체여부',detail:'세부 고장내용',actionTaken:'조치내용',note:'비고',inputSource:'입력 출처',createdAt:'생성일시',updatedAt:'수정일시'};
function localized<T extends object>(data:T[],headers:Record<keyof T,string>){return data.map(row=>Object.fromEntries((Object.keys(headers) as Array<keyof T>).map(k=>[headers[k],row[k]])));}
export function downloadWorkbook(name:string,sheets:{name:string;data:object[]}[]){const wb=XLSX.utils.book_new();sheets.forEach(s=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(s.data),s.name.slice(0,31)));XLSX.writeFile(wb,name+'_'+new Date().toISOString().slice(0,10)+'.xlsx');}
export const exportTm=(t:TmMaster[],r:RiskScore[])=>localized(t.map(tm=>{const risk=r.find(x=>x.serialNo===tm.serialNo);return{...tm,inferredFromReplacement:tm.inferredFromReplacement?'Y':'N',...risk,isUncertain:risk?.isUncertain?'불분명':'',uncertaintyReasons:risk?.uncertaintyReasons?.join(', ')??''};}),{...tmHeaders,AScore:'A_score',FScore:'F_score',TScore:'T_score',MScore:'M_score',riskScore:'Risk_Score',riskGrade:'위험등급',calculatedAt:'계산일시',isUncertain:'불분명 여부',uncertaintyReasons:'불분명 사유',formulaVersion:'산식 버전'} as never);
export const exportHistory=(h:ReplacementHistory[])=>localized(h,replacementHeaders);
export const exportRisks=(r:RiskScore[])=>r.map(v=>({'시리얼번호':v.serialNo,'노후도 점수(A)':v.AScore,'고장빈도 점수(F)':v.FScore,'심각도 점수(T)':v.TScore,'MKBF 점수(M)':v.MScore,'최종 위험도':v.riskScore,'위험등급':v.riskGrade,'불분명 여부':v.isUncertain?'불분명':'','불분명 사유':v.uncertaintyReasons?.join(', ')??'','계산일시':v.calculatedAt}));
export const exportIssues=(v:ValidationIssue[])=>v.map(x=>({'수준':x.level,'오류유형':x.category,'시트명':x.sheetName??'','행':x.row??'','시리얼번호':x.serialNo??'','검증 내용':x.message,'처리 권장사항':x.recommendation??''}));
