import * as XLSX from 'xlsx';import type { TmMaster } from '../types/tm';import type { ReplacementHistory } from '../types/replacement';import type { RiskScore,ValidationIssue } from '../types/risk';
export interface ParsedWorkbook{fileName:string;sheetNames:string[];selectedSheet:string;headers:string[];rows:Record<string,unknown>[];headerRow:number;raw:Array<Array<unknown>>;}
const text=(v:unknown)=>v==null?'':String(v).trim();const num=(v:unknown)=>{const s=text(v).replace(/,/g,'');const n=Number(s);return Number.isFinite(n)?n:null;};
const date=(v:unknown)=>{if(!v)return'';if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:'';}const s=text(v).replace(/[./]/g,'-');const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toISOString().slice(0,10);};
const uniqueHeaders=(row:Array<unknown>)=>{const seen=new Map<string,number>();return row.map((v,i)=>{const base=text(v)||`빈컬럼${i+1}`;const count=seen.get(base)??0;seen.set(base,count+1);return count?`${base}_${count+1}`:base;});};
export async function parseWorkbook(file:File,sheetName?:string):Promise<ParsedWorkbook>{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const selectedSheet=sheetName&&wb.Sheets[sheetName]?sheetName:wb.SheetNames[0];const raw=XLSX.utils.sheet_to_json<Array<unknown>>(wb.Sheets[selectedSheet],{header:1,defval:'',raw:false});let headerRow=0,best=-1;raw.slice(0,25).forEach((r,i)=>{const filled=r.filter(v=>text(v)).length;const labelScore=r.filter(v=>/[가-힣A-Za-z]/.test(text(v))).length;const score=filled+labelScore;if(score>best){best=score;headerRow=i;}});const headers=uniqueHeaders(raw[headerRow]??[]);const rows=raw.slice(headerRow+1).filter(r=>r.some(v=>text(v))).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));return{fileName:file.name,sheetNames:wb.SheetNames,selectedSheet,headers,rows,headerRow:headerRow+1,raw};}
export function mapTmRows(rows:Record<string,unknown>[],m:Record<string,string>,referenceYear:number):TmMaster[]{const now=new Date().toISOString();return rows.map<TmMaster>(r=>{const year=num(r[m.manufactureYear]);const status=text(r[m.currentStatus])||'상태미상';const spare=['예','y','true','1','예비품'].includes(text(r[m.isSpare]).toLowerCase())||status.includes('예비');return{serialNo:text(r[m.serialNo]),manufacturer:text(r[m.manufacturer]),manufactureYear:year,ageYear:year?Math.max(0,referenceYear-year):0,currentStatus:status,isSpare:spare,currentTrain:text(r[m.currentTrain]),currentCar:text(r[m.currentCar]),currentPosition:text(r[m.currentPosition]),installDate:date(r[m.installDate]),sourceType:'current_excel',note:text(r[m.note]),createdAt:now,updatedAt:now};}).filter(v=>v.serialNo&&v.serialNo!=='-');}
export function mapReplacementRows(rows:Record<string,unknown>[],m:Record<string,string>):ReplacementHistory[]{const now=new Date().toISOString();return rows.map<ReplacementHistory>(r=>({replacementId:text(r[m.replacementId])||crypto.randomUUID(),replacementDate:date(r[m.replacementDate]),trainNo:text(r[m.trainNo]),carNo:text(r[m.carNo]),position:text(r[m.position]),removedSerialNo:text(r[m.removedSerialNo]),removedManufactureYear:num(r[m.removedManufactureYear]),removedManufacturer:text(r[m.removedManufacturer]),removedStatus:text(r[m.removedStatus]),installedSerialNo:text(r[m.installedSerialNo]),installedManufactureYear:num(r[m.installedManufactureYear]),installedManufacturer:text(r[m.installedManufacturer]),installedStatus:text(r[m.installedStatus]),replacementReason:text(r[m.replacementReason]),failureType:text(r[m.failureType]),severityClass:text(r[m.severityClass]),severityScore:num(r[m.severityScore]),detail:text(r[m.detail]),actionTaken:text(r[m.actionTaken]),note:text(r[m.note]),inputSource:'history_excel',createdAt:now,updatedAt:now})).filter(v=>(v.replacementDate||v.removedSerialNo||v.installedSerialNo)&&(v.removedSerialNo!=='-'||v.installedSerialNo!=='-'));}
const tmHeaders:Record<keyof TmMaster,string>={serialNo:'시리얼번호',manufacturer:'제조사',manufactureYear:'제작년도',ageYear:'사용연수',currentStatus:'현재상태',isSpare:'예비품 여부',currentTrain:'편성',currentCar:'호차',currentPosition:'위치',installDate:'취부일자',sourceType:'데이터 출처',note:'비고',createdAt:'생성일시',updatedAt:'수정일시'};
const replacementHeaders:Record<keyof ReplacementHistory,string>={replacementId:'교체 ID',replacementDate:'교체일자',trainNo:'편성',carNo:'호차',position:'위치',removedSerialNo:'취거 TM',removedManufactureYear:'취거 TM 제작년도',removedManufacturer:'취거 TM 제조사',removedStatus:'취거품 상태',installedSerialNo:'취부 TM',installedManufactureYear:'취부 TM 제작년도',installedManufacturer:'취부 TM 제조사',installedStatus:'취부품 상태',replacementReason:'교체사유',failureType:'고장유형',severityClass:'고장심각도',severityScore:'심각도 점수',detail:'세부 고장내용',actionTaken:'조치내용',note:'비고',inputSource:'입력 출처',createdAt:'생성일시',updatedAt:'수정일시'};
function localized<T extends object>(data:T[],headers:Record<keyof T,string>){return data.map(row=>Object.fromEntries((Object.keys(headers) as Array<keyof T>).map(k=>[headers[k],row[k]])));}
export function downloadWorkbook(name:string,sheets:{name:string;data:object[]}[]){const wb=XLSX.utils.book_new();sheets.forEach(s=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(s.data),s.name.slice(0,31)));XLSX.writeFile(wb,`${name}_${new Date().toISOString().slice(0,10)}.xlsx`);}
export const exportTm=(t:TmMaster[],r:RiskScore[])=>localized(t.map(tm=>({...tm,...r.find(x=>x.serialNo===tm.serialNo)})),{...tmHeaders,AScore:'노후도 점수(A)',FScore:'고장빈도 점수(F)',TScore:'심각도 점수(T)',MScore:'MKBF 점수(M)',riskScore:'최종 위험도',riskGrade:'위험등급',calculatedAt:'계산일시',formulaVersion:'산식 버전'} as never);
export const exportHistory=(h:ReplacementHistory[])=>localized(h,replacementHeaders);
export const exportRisks=(r:RiskScore[])=>r.map(v=>({'시리얼번호':v.serialNo,'노후도 점수(A)':v.AScore,'고장빈도 점수(F)':v.FScore,'심각도 점수(T)':v.TScore,'MKBF 점수(M)':v.MScore,'최종 위험도':v.riskScore,'위험등급':v.riskGrade,'계산일시':v.calculatedAt}));
export const exportIssues=(v:ValidationIssue[])=>v.map(x=>({'수준':x.level,'오류유형':x.category,'행':x.row??'','시리얼번호':x.serialNo??'','내용':x.message}));
